---
  - name: Patch proftpd
    vars:
      ansible_python_interpreter: /usr/bin/python3
    hosts: machine_to_patch
    tasks:
      - name: Stop proftpd docker-compose
        community.docker.docker_compose:
          project_src: /home/admin/m1
          build: no
          stopped: yes

      - name: Remove old proftpd Dockerfile and directory
        file:
          state: absent
          path: /home/admin/m1/proftpd-1.3.5
      
      - name: Create directory for proftpd
        file:
          path: /home/admin/m1/proftpd-1.3.8
          state: directory
      
      - name: Upload patched Dockerfile for proftpd
        ansible.builtin.copy:
          src:  "./src/Dockerfile"
          dest: "/home/admin/m1/proftpd-1.3.8/"
      
      - name: Remove docker-compose file
        file:
          path: /home/admin/m1/docker-compose.yml
          state: absent
      
      - name: Upload patched docker-compose
        ansible.builtin.copy:
          src:  "./src/docker-compose.yml"
          dest: "/home/admin/m1/"
      
      - name: Restart docker-compose
        community.docker.docker_compose:
          project_src: /home/admin/m1
          build: yes