version: "3"

services:

  flatfile:
    build: ./flatfilelogin
    volumes:
      - /tmp/data/:/usr/share/nginx/html/:rw
    networks:
      - flatnginx
    restart: always
  proftpd:
    build: ./proftpd-1.3.8
    volumes:
      - /tmp/data/:/usr/share/nginx/html/:rw
    restart: always
    ports:
      - "21:21"
  nginx:
    build: ./proxy
    depends_on:
      - flatfile
    environment:
      FLATFILELOGIN_HOST: flatfile
    ports:
      - 80:80
    networks:
      - flatnginx
    restart: always
networks:
  flatnginx:
    driver: bridge
